[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
app-core = { path = "crates/app-core", version = "*" }

[profile.release]
strip = "debuginfo"
opt-level = 2

[profile.production]
inherits = "release"
strip = "symbols"
codegen-units = 1