[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# default_plugins.workspace = true
app-core.workspace = true
egui-macroquad = "0.15.0"

[target.'cfg(not(wasm))'.dependencies]
libloading = "0.8.3"

[target.'cfg(wasm)'.dependencies]
default-plugins.workspace = true