[package]
name = "app-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
libloading = "0.8.3"
egui-macroquad = "0.15.0"
rustc-hash = "1.1.0"
