[build]
# rustflags = "-C prefer_dynamic"

#  cargo build -Z build-std --target x86_64-pc-windows-msvc --release


# rustflags = "Zlocation-detail=none +nightly -Z build-std=std --target x86_64-pc-windows-msvc -C prefer_dynamic"
# rustflags = ["-C", "prefer_dynamic"]
# rustflags = ["-Zlocation-detail=none","+nightly","-Z","build-std=std","-C", "prefer_dynamic"]

