[package]
name = "js-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
app-core.workspace = true
serde_json = "*"
serde = {version = "1.0.197", features = ["derive"]}

[lib]
crate-type = ["lib"]
